#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions -std=c++20 -fopenmp
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = lib/libPetroleum.a -lGLEW -lX11 -lGLU -lGL -lglfw -fopenmp

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g -DDEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/chess-gui

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -Ofast
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/chess-gui

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/UI.o $(OBJDIR_DEBUG)/src/Renderer.o $(OBJDIR_DEBUG)/src/Position.o $(OBJDIR_DEBUG)/src/Piece.o $(OBJDIR_DEBUG)/src/PGN.o $(OBJDIR_DEBUG)/src/Move.o $(OBJDIR_DEBUG)/src/Evaluation.o $(OBJDIR_DEBUG)/src/Board.o $(OBJDIR_DEBUG)/src/AI.o $(OBJDIR_DEBUG)/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/UI.o $(OBJDIR_RELEASE)/src/Renderer.o $(OBJDIR_RELEASE)/src/Position.o $(OBJDIR_RELEASE)/src/Piece.o $(OBJDIR_RELEASE)/src/PGN.o $(OBJDIR_RELEASE)/src/Move.o $(OBJDIR_RELEASE)/src/Evaluation.o $(OBJDIR_RELEASE)/src/Board.o $(OBJDIR_RELEASE)/src/AI.o $(OBJDIR_RELEASE)/main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/UI.o: src/UI.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/UI.cpp -o $(OBJDIR_DEBUG)/src/UI.o

$(OBJDIR_DEBUG)/src/Renderer.o: src/Renderer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Renderer.cpp -o $(OBJDIR_DEBUG)/src/Renderer.o

$(OBJDIR_DEBUG)/src/Position.o: src/Position.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Position.cpp -o $(OBJDIR_DEBUG)/src/Position.o

$(OBJDIR_DEBUG)/src/Piece.o: src/Piece.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Piece.cpp -o $(OBJDIR_DEBUG)/src/Piece.o

$(OBJDIR_DEBUG)/src/PGN.o: src/PGN.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PGN.cpp -o $(OBJDIR_DEBUG)/src/PGN.o

$(OBJDIR_DEBUG)/src/Move.o: src/Move.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Move.cpp -o $(OBJDIR_DEBUG)/src/Move.o

$(OBJDIR_DEBUG)/src/Evaluation.o: src/Evaluation.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Evaluation.cpp -o $(OBJDIR_DEBUG)/src/Evaluation.o

$(OBJDIR_DEBUG)/src/Board.o: src/Board.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Board.cpp -o $(OBJDIR_DEBUG)/src/Board.o

$(OBJDIR_DEBUG)/src/AI.o: src/AI.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AI.cpp -o $(OBJDIR_DEBUG)/src/AI.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/UI.o: src/UI.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/UI.cpp -o $(OBJDIR_RELEASE)/src/UI.o

$(OBJDIR_RELEASE)/src/Renderer.o: src/Renderer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Renderer.cpp -o $(OBJDIR_RELEASE)/src/Renderer.o

$(OBJDIR_RELEASE)/src/Position.o: src/Position.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Position.cpp -o $(OBJDIR_RELEASE)/src/Position.o

$(OBJDIR_RELEASE)/src/Piece.o: src/Piece.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Piece.cpp -o $(OBJDIR_RELEASE)/src/Piece.o

$(OBJDIR_RELEASE)/src/PGN.o: src/PGN.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/PGN.cpp -o $(OBJDIR_RELEASE)/src/PGN.o

$(OBJDIR_RELEASE)/src/Move.o: src/Move.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Move.cpp -o $(OBJDIR_RELEASE)/src/Move.o

$(OBJDIR_RELEASE)/src/Evaluation.o: src/Evaluation.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Evaluation.cpp -o $(OBJDIR_RELEASE)/src/Evaluation.o

$(OBJDIR_RELEASE)/src/Board.o: src/Board.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Board.cpp -o $(OBJDIR_RELEASE)/src/Board.o

$(OBJDIR_RELEASE)/src/AI.o: src/AI.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AI.cpp -o $(OBJDIR_RELEASE)/src/AI.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

